### ISSUE TITLE
Regression: Default log file option causes crash

### ISSUE THREAD

**Issue by m6sec** [maurosoria/dirsearch#1034]
### What is the current behavior?
The application is crashing when called like this:
`/home/kali/TOOLS/dirsearch/dirsearch.py -r -u https://example.com `

The error message is:
```
  _|. _ _  _  _  _ _|_    v0.4.2.1
 (_||| _) (/_(_|| (_| )

Extensions: php, aspx, jsp, html, js | HTTP method: GET | Threads: 25 | Wordlist size: 11302

Output File: /home/kali/TOOLS/dirsearch/reports/example.com/_22-01-25_16-39-46.txt
Traceback (most recent call last):
  File "/home/kali/TOOLS/dirsearch/dirsearch.py", line 46, in <module>
    main = Program()
  File "/home/kali/TOOLS/dirsearch/dirsearch.py", line 42, in __init__
    Controller(options, output)
  File "/home/kali/TOOLS/dirsearch/lib/controller/controller.py", line 123, in __init__
    self.validate_dir(FileUtils.parent(options.log_file))
  File "/home/kali/TOOLS/dirsearch/lib/controller/controller.py", line 297, in validate_dir
    self.validate_output_loc(FileUtils.parent(path))
AttributeError: 'Controller' object has no attribute 'validate_output_loc'
```
The default config (default.conf) sets options.log_file to 'logs/last_scan.log', which usually does not exist in whatever directory one is calling this application. Therefore when trying to validate the log file location the above error occurs. Additionally, the function validate_output_loc does not exist and I'm not entirely clear what is would be supposed to do.

### What is the expected behavior?

I'd think it should be one of the following three options by default, unless specified otherwise:
* write log file into the app dir (like it was previously for log files and is done for reports - probably not the best practice though).
* write log file in the current directory
* do not write a log file at all, unless --log is set

### Any additional information?
This behavior was introduced with commit e20bd79d5d9b213f2df773643882065b2904a0d6

#### Checker:
 - [x] I tested in the latest version of dirsearch
